# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0ddb7bf316136d0ae7f48d6fd15a22a4af6888858138ccc915aa7c8713d18272aeb36ae78b0ee2aa9704027d367265cc16597cd2f9b5e9dbc8a0ad4d55773c

test:
  secret_key_base: c5b9f476083892b69a2c77f8a3be43f10d1001d6c6e3501e95bfd179066f6b846259e6674e6ebb2f087a144a93f4a1bab8e604941e928be96996a63f41a0df1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
